# Generated by Django 2.1.7 on 2019-03-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.Office'),
            preserve_default=False,
        ),
    ]
