# Generated by Django 2.1.7 on 2019-03-10 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_recieved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recieved',
            new_name='Recieve',
        ),
    ]
