# Generated by Django 2.1.7 on 2019-03-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_itemcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCode',
        ),
    ]
