# Generated by Django 2.1.7 on 2019-03-10 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190310_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 10, 20, 6, 14, 410924), null=True),
        ),
    ]
