# Generated by Django 2.1.7 on 2019-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_delete_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.ImageField(default=None, upload_to='media'),
            preserve_default=False,
        ),
    ]
