# Generated by Django 2.1.7 on 2019-03-10 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190310_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 10, 20, 8, 36, 599984), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
