# Generated by Django 2.1.7 on 2019-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190311_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('Consumables', 'Consumables'), ('Non-Consumables', 'Non-Consumables')], default=None, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='single', max_length=9),
        ),
    ]
