# Generated by Django 2.1.7 on 2019-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190301_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_cost',
            field=models.IntegerField(),
        ),
    ]
