# Generated by Django 2.1.7 on 2019-03-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20190311_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('Consumables', 'Consumables'), ('Non-Consumables', 'Non-Consumables')], max_length=20),
        ),
    ]
