# Generated by Django 2.1.7 on 2019-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20190301_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('separeted', 'separeted'), ('widow', 'widow')], default='single', max_length=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], default='1st', max_length=9),
        ),
        migrations.AlterField(
            model_name='release',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
